---
- hosts: all

  vars_files:
    - default.config.yml

  vars_prompt:
    - name: mas_email
      prompt: Enter Apple ID
      private: no

  pre_tasks:
    - include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"
      tags: ['always']
      
    - name: Fix brew cask issue
      get_url:
        url: "{{ item.from }}"
        dest: "{{ item.to }}"
      with_items:
        - { from: 'https://raw.githubusercontent.com/ansible-collections/community.general/2980440bafdf52091555c148f940c856c3807015/plugins/modules/packaging/os/homebrew_cask.py', to: '/usr/local/Cellar/ansible/2.10.4/libexec/lib/python3.9/site-packages/ansible_collections/community/general/plugins/modules/packaging/os/homebrew_cask.py' }
        - { from: 'https://raw.githubusercontent.com/ansible-collections/community.general/2980440bafdf52091555c148f940c856c3807015/plugins/modules/packaging/os/homebrew_cask.py', to: '/usr/local/Cellar/ansible/2.10.4/libexec/lib/python3.9/site-packages/ansible_collections/community/general/plugins/modules/homebrew_cask.py' }

  roles:
    - role: geerlingguy.homebrew
      tags: ['homebrew']
    - role: geerlingguy.dotfiles
      when: configure_dotfiles
      tags: ['dotfiles']
    - role: geerlingguy.mas
      when: mas_installed_apps
      tags: ['mas']

  tasks:
    - include_tasks: tasks/ansible-setup.yml

    - include_tasks: tasks/sudoers.yml
      when: configure_sudoers

    - include_tasks: tasks/terminal.yml
      when: configure_terminal

    - include_tasks: tasks/osx.yml
      when: configure_osx
      tags: ['osx']

    - include_tasks: tasks/extra-packages.yml
      tags: ['extra-packages']

    - name: Run configured post-provision ansible task files.
      include_tasks: "{{ outer_item }}"
      loop_control:
        loop_var: outer_item
      with_fileglob: "{{ post_provision_tasks|default(omit) }}"