---
roles:
  - name: elliotweiser.osx-command-line-tools
  - name: geerlingguy.dotfiles
  - name: geerlingguy.mas
  - src: git@github.com:drew-kun/ansible-macdock.git
    scm: git

collections:
  - name: geerlingguy.mac
